### ISSUE TITLE
Broken Button Panel

### ISSUE THREAD

**Issue by themattliberty** [danthegoodman/pingpong#4]
### Problem

The button panel on the entrance side of the table is broken.
### Steps to reproduce
1. Enter the ping-pong room
2. Look at the ping-pong table

**Comment by danthegoodman** [comment]
Hmm... I'm going to need some photographic evidence for this.

**Comment by themattliberty** [comment]
![ping-pong-table](https://cloud.githubusercontent.com/assets/5051041/6564796/7639af7a-c679-11e4-8789-24ef83a22b76.jpg)

**Comment by danthegoodman** [comment]
:scream:

**Comment by themattliberty** [comment]
Kevin has resolved this issue.

**Comment by danthegoodman** [comment]
thanks @kmill1337 !

**Comment by kmill1337** [comment]
This is a temporary fix. We may want to look into a different design in the future, but this should hold for now
